title: Oleg Shevchenko's blog
email: olsh.me@gmail.com
description: >-
  Hello, I'm Oleg
baseurl: ""
url: "https://olsh.me"

markdown: kramdown
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-feed
  - jekyll-sitemap

google_analytics: UA-49608104-1

footer_links:
  - title: GitHub
    url: https://github.com/olsh
    icon: fab fa-github-square
  - title: Twitter
    url: https://twitter.com/olshme
    icon: fab fa-twitter-square
  - title: LinkedIn
    url: https://www.linkedin.com/in/olshme/
    icon: fab fa-linkedin
  - title: Feed
    url: feed.xml
    icon: fas fa-rss-square

copyright: "© 2018 Oleg Shevchenko"

read_time: false

disqus:
  shortname: olsh-me
